apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-demo
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 8080
    targetPort: 80
  selector:
    app: nginx-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx:1.23 
        imagePullPolicy: Always
